### PR TITLE
Improve ByteString safety and add [isValid, normalise, equalFilePath] functions

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
Is this project still active?

**Comment by nh2** [comment]
@JohnLato Do you actively maintain `posix-paths` currently? If not, I _might_ take it over (though I'm also quite busy).

**Comment by hasufell** [comment]
I guess I'll fork this library on hackage then.

**Comment by hvr** [comment]
@nh2 @hasufell have you tried contacting @JohnLato via other means (e.g. email) as well? He may not get/notice GitHub notifications...

**Comment by nh2** [comment]
I've pinged him on email just now.

**Comment by hasufell** [comment]
I've forked this library (along with the [path](https://hackage.haskell.org/package/path) library) into [hpath](https://hackage.haskell.org/package/hpath) to create a consistent set of functionality for safe and well-typed paths. Since that includes some API breaking changes (e.g. by fixing #18) I guess it's better for me to continue there, which also allows me to move forward more quickly.

**Comment by JohnLato** [comment]
So it turns out that I wasn't getting github notifications, I need to check why but I probably have a rogue filter somewhere.

I am rather busy and not really giving any of my packages the attention they deserve (although I thought I'd already fixed #18 ).  @hasufell if you're interested, why don't I add you as a collaborator and give you Hackage permissions for posix-paths?

**Comment by hasufell** [comment]
Well yeah, I could give it a shot and backport what I have done in the fork.

**Pull request closed without merging**
